import cv2
img = cv2.imread('C:\\Users\\pc\\Downloads\\cheast_cw_image.jpg')
cv2.imshow("original",img)
#cv2.waitkey(0)
gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow("grayscale",gray)
height,width = gray.shape
sobel_x = cv2.Sobel(gray,cv2.CV_64F,1,0,ksize =5)
sobel_y = cv2.Sobel(gray,cv2.CV_64F,0,1,ksize =5)
cv2.imshow("sobel x",sobel_x)
#cv2.waitkey(0)
cv2.imshow("sobel y",sobel_y)
#cv2.waitkey(0)
sobel_Or = cv2.bitwise_or(sobel_x,sobel_y)
cv2.imshow("sobel or",sobel_Or)
#cv2.waitkey(0)
canny = cv2.Canny(gray,0,255)
cv2.imshow("canny",canny)
#cv2.waitkey(0)
laplacian= cv2.Laplacian(gray,cv2.CV_64F)
cv2.imshow("laplacian",laplacian)
#cv2.waitkey(0)
